/*
 * main.h
 *
 * Created: 11-Jun-24 1:41:08 PM
 *  Author: ranul
 */ 

#ifndef MAIN_H_
#define MAIN_H_

#define REGISTER_MEMORY_SIZE 30
#define COMMAND_MAP_READ_RANGE_LOW 0 
#define COMMAND_MAP_READ_RANGE_HIGH 127
#define COMMAND_MAP_WRITE_RANGE_LOW 128
#define COMMAND_MAP_WRITE_RANGE_HIGH 255

#define ONE_BYTE 1
#define TWO_BYTES 2

enum COMMAND_MAP {
	COMMAND_READ_INPUT_VOLTAGE,
	COMMAND_READ_BRAKE_SWITCH_STATE,
	COMMAND_READ_WARNING_LAMP_STATE,
	COMMAND_READ_FAULT_CODE,
	COMMAND_READ_CONTROLLER_VOLTAGE,
	COMMAND_READ_CONTROLLER_STATUS_CODE,
	COMMAND_READ_SOLENOID_FL_STATE,
	COMMAND_READ_SOLENOID_FL_VOLTAGE,
	COMMAND_READ_SOLENOID_FL_CURRENT,
	COMMAND_READ_SOLENOID_FL_RESISTANCE,
	COMMAND_READ_SOLENOID_FR_STATE,
	COMMAND_READ_SOLENOID_FR_VOLTAGE,
	COMMAND_READ_SOLENOID_FR_CURRENT,
	COMMAND_READ_SOLENOID_FR_RESISTANCE,
	COMMAND_READ_SOLENOID_RL_STATE,
	COMMAND_READ_SOLENOID_RL_VOLTAGE,
	COMMAND_READ_SOLENOID_RL_CURRENT,
	COMMAND_READ_SOLENOID_RL_RESISTANCE,
	COMMAND_READ_SOLENOID_RR_STATE,
	COMMAND_READ_SOLENOID_RR_VOLTAGE,
	COMMAND_READ_SOLENOID_RR_CURRENT,
	COMMAND_READ_SOLENOID_RR_RESISTANCE,
	COMMAND_READ_MOTOR_STATE,
	COMMAND_READ_MOTOR_VOLTAGE,
	COMMAND_READ_MOTOR_CURRENT,
	COMMAND_READ_MOTOR_RPM,
	COMMAND_READ_MOTOR_DIRECTION,
	COMMAND_READ_MOTOR_TEMPERATURE
};

enum REGISTER_MAP {
	REGISTER_READ_INPUT_VOLTAGE_HIGH,
	REGISTER_READ_INPUT_VOLTAGE_LOW,
	REGISTER_READ_BRAKE_SWITCH_STATE,
	REGISTER_READ_WARNING_LAMP_STATE,
	REGISTER_READ_FAULT_CODE,
	REGISTER_READ_CONTROLLER_VOLTAGE_HIGH,
	REGISTER_READ_CONTROLLER_VOLTAGE_LOW,
	REGISTER_READ_CONTROLLER_STATUS_CODE,
	REGISTER_READ_SOLENOID_FL_STATE,
	REGISTER_READ_SOLENOID_FL_VOLTAGE,
	REGISTER_READ_SOLENOID_FL_CURRENT,
	REGISTER_READ_SOLENOID_FL_RESISTANCE,
	REGISTER_READ_SOLENOID_FR_STATE,
	REGISTER_READ_SOLENOID_FR_VOLTAGE,
	REGISTER_READ_SOLENOID_FR_CURRENT,
	REGISTER_READ_SOLENOID_FR_RESISTANCE,
	REGISTER_READ_SOLENOID_RL_STATE,
	REGISTER_READ_SOLENOID_RL_VOLTAGE,
	REGISTER_READ_SOLENOID_RL_CURRENT,
	REGISTER_READ_SOLENOID_RL_RESISTANCE,
	REGISTER_READ_SOLENOID_RR_STATE,
	REGISTER_READ_SOLENOID_RR_VOLTAGE,
	REGISTER_READ_SOLENOID_RR_CURRENT,
	REGISTER_READ_SOLENOID_RR_RESISTANCE,
	REGISTER_READ_MOTOR_STATE,
	REGISTER_READ_MOTOR_VOLTAGE,
	REGISTER_READ_MOTOR_CURRENT,
	REGISTER_READ_MOTOR_RPM,
	REGISTER_READ_MOTOR_DIRECTION,
	REGISTER_READ_MOTOR_TEMPERATURE
};

//uint8_t *readRegister(uint8_t address);
void commandDecoder(uint8_t command);
//void sendData(uint8_t *data, uint8_t length);

uint8_t readRegister(uint8_t address);
void sendData(uint8_t data, uint8_t length);

#endif /* MAIN_H_ */